W5D1/Reddit/config/routes.rb
Rails.application.routes.draw do

  resources :users, only: [:create, :new, :show]

  resource :session, only: [:create, :destroy, :new]

  resources :subs
end

W5D1/Reddit/app/models/sub.rb
# == Schema Information
#
# Table name: subs
#
#  id          :integer          not null, primary key
#  title       :string           not null
#  description :text
#  mod_id      :integer          not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Sub < ActiveRecord::Base
  # before_action :is_moderator?

  validates :title, :mod_id, presence: true, uniqueness: true

  def is_moderator?(id)
    self.mod_id == id
    #potential_sub = Sub.find_by(mod_id: id)
  end

end

W5D1/Reddit/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  validates :username, uniqueness: true
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  after_initialize :ensure_session_token

  attr_reader :password

  def ensure_session_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end

  def self.find_by_credentials(username, password)
    possible_user = User.find_by(username: username)
    return nil unless possible_user
    possible_user.is_password?(password) ? possible_user : nil
  end

  def is_password?(password)
    bc = BCrypt::Password.new(self.password_digest)
    bc.is_password?(password)
  end

  def password=(password)
    @password = password
    password_digest = BCrypt::Password.create(password)
    self.password_digest = password_digest
  end

  def reset_session_token!
    self.session_token = SecureRandom.urlsafe_base64
    self.save!
    self.session_token
  end
end

W5D1/Reddit/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def login(user)
    session[:session_token] = user.session_token
  end

  def logout(user)
    user.reset_session_token!
    session[:session_token] = nil
  end

  # def logged_in?
  #   !!current_user
  # end

  def current_user
    @current_user = User.find_by(session_token: session[:session_token])
  end
end

W5D1/Reddit/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    @user = User.find_by_credentials(session_params[:username],
      session_params[:password])
    if @user
      login(@user)
      redirect_to user_url(@user)
    else
      flash[:errors] = @user.errors.full_messages
      redirect_to new_session_url
    end
  end

  def destroy
    logout(current_user)
    redirect_to new_session_url
  end

  def new
  end



  private
  def session_params
    params.require(:user).permit(:username, :password)
  end

end

W5D1/Reddit/app/controllers/subs_controller.rb
class SubsController < ApplicationController

  def index
  end

  def create
    new_sub = Sub.new(sub_params)
    new_sub.mod_id = current_user.id
    if new_sub.save
      redirect_to sub_url(new_sub)
    else
      flash[:errors] = sub_new.errors.full_messages
      redirect_to new_sub_url
    end
  end

  def new
    if current_user
      render :new
    else
      redirect_to new_session_url
    end
  end

  def edit
    @potential_subs = Sub.find(params[:id])
    user_id = current_user.id
    if @potential_subs && @potential_subs.is_moderator?(user_id)
      render :edit
    else
      redirect_to subs_url
    end
  end

  def show
  end

  def update
    sub_update = Sub.find(params[:id])
    sub_update.update(sub_params)

  end

  private
  def sub_params
    params.require(:sub).permit(:title, :description)
  end
end

W5D1/Reddit/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @user = User.new(user_params)
    if @user.valid?
      @user.save
      login(@user)
      redirect_to user_url(@user)
    else
      flash[:username] = params[:user][:username]
       flash[:errors] = @user.errors.full_messages
      redirect_to new_user_url
    end
  end

  def show

    if current_user && current_user.id == params[:id].to_i
      @user = User.find(params[:id])
      render :show
    else
      redirect_to new_session_url
    end
  end

  def new
  end

  private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end

W5D1/Reddit/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Reddit</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<% if current_user %>
<%= button_to "Logout", session_url, method: :delete %>
<% end %>

<% if flash[:errors] %>
<ul>
  <% flash[:errors].each do |error_msg| %>
  <li><%= error_msg %></li>
  <% end %>
</ul>
<% end %>

<%= yield %>

</body>
</html>

W5D1/Reddit/app/views/subs/edit.html.erb
<h1>Edit sub</h1>

<form action= "/subs/<%= @potential_subs.id %>" method="POST">
  <input
    type="hidden"
    name="_method"
    value="PATCH">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

    <label for="sub_t">Title</label>
    <br>
    <input type="text" name="sub[title]" value="<%= @potential_subs.title %>" id="sub_t">
    <br>
    <br>
    <label for="sub_d">Description</label>
    <br>
    <textarea name="sub[description]" value="<%= @potential_subs.description %>" id="sub_d"></textarea>
    <br>
    <br>
    <input type="submit" value="Update">
</form>

W5D1/Reddit/app/views/subs/new.html.erb
<h1>Create a sub</h1>

<form action= "/subs" method="POST">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

    <label for="sub_t">Title</label>
    <br>
    <input type="text" name="sub[title]" id="sub_t">
    <br>
    <br>
    <label for="sub_d">Description</label>
    <br>
    <textarea name="sub[description]" id="sub_d"></textarea>
    <br>
    <br>
    <input type="submit" value="Create">
</form>

W5D1/Reddit/app/views/subs/show.html.erb
<h1>We did it</h1>

W5D1/Reddit/app/views/users/new.html.erb
<h1>Sign Up for Reddit you won't regret it!</h1>

<form action="/users" method="post">
  <input
    type="hidden"
    name="authenticity_token"
    value="<%= form_authenticity_token %>">

<p>
  <label>Username
    <input type="text" name="user[username]"value=" <%= flash[:username] %>" >
  </label>
</p>

<p>
  <label>Password
    <input type="password" name="user[password]">
  </label>
</p>

<input type="submit">

</form>

W5D1/Reddit/app/views/users/show.html.erb
<h1>Welcome <%= current_user.username.capitalize %>! </h1>